"""
    x402api Public API

    Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "x402api"
VERSION = "0.1.0"
PYTHON_REQUIRES = ">= 3.10"
REQUIRES = [
    "urllib3 >= 2.6.3, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2.11",
    "typing-extensions >= 4.7.1",
    "lazy-imports >= 1, < 2",
]

setup(
    name=NAME,
    version=VERSION,
    description="x402api Public API",
    author="OpenAPI Generator community",
    author_email="team@openapitools.org",
    url="https://github.com/x402api-com/x402api-python",
    keywords=["OpenAPI", "OpenAPI-Generator", "x402api Public API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type='text/markdown',
    long_description="""\
    Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.
    """,  # noqa: E501
    package_data={"x402api": ["py.typed"]},
)
