# coding: utf-8

"""
    x402api Public API

    Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from x402api.models.observation_block import ObservationBlock
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BalanceAsset(BaseModel):
    """
    BalanceAsset
    """ # noqa: E501
    asset_id: StrictStr
    display_name: StrictStr
    symbol: StrictStr
    contract_address: StrictStr
    decimals: StrictInt
    amount_atomic: StrictStr
    amount: StrictStr
    issuer_native: StrictBool
    observed_at: datetime
    node_source: StrictStr
    source_consensus: StrictStr
    block: ObservationBlock
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["asset_id", "display_name", "symbol", "contract_address", "decimals", "amount_atomic", "amount", "issuer_native", "observed_at", "node_source", "source_consensus", "block"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BalanceAsset from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of block
        if self.block:
            _dict['block'] = self.block.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BalanceAsset from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "asset_id": obj.get("asset_id"),
            "display_name": obj.get("display_name"),
            "symbol": obj.get("symbol"),
            "contract_address": obj.get("contract_address"),
            "decimals": obj.get("decimals"),
            "amount_atomic": obj.get("amount_atomic"),
            "amount": obj.get("amount"),
            "issuer_native": obj.get("issuer_native"),
            "observed_at": obj.get("observed_at"),
            "node_source": obj.get("node_source"),
            "source_consensus": obj.get("source_consensus"),
            "block": ObservationBlock.from_dict(obj["block"]) if obj.get("block") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
