# coding: utf-8

"""
    x402api Public API

    Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from x402api.models.dynamic_charge_price import DynamicChargePrice
from x402api.models.public_fee_policy_document import PublicFeePolicyDocument
from x402api.models.public_network_fee_alternative import PublicNetworkFeeAlternative
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DynamicChargeResponse(BaseModel):
    """
    DynamicChargeResponse
    """ # noqa: E501
    charge_id: UUID = Field(description="Immutable challenge UUID created for this charge.")
    charge_digest: Annotated[str, Field(strict=True)]
    order_id: UUID
    status: StrictStr = Field(description="Current projected order status; payment terms remain immutable.")
    resource_version_id: UUID
    payment_identifier: StrictStr = Field(description="Opaque server challenge handle. Return it to the buyer as X-X402API-Challenge-Handle; it is not the buyer payment identifier.")
    expires_at: datetime
    created_at: datetime
    prices: List[DynamicChargePrice]
    requested_expires_in_seconds: StrictInt
    metadata: Dict[str, Any] = Field(description="Tenant application metadata frozen into the charge digest. Maximum canonical size is 16 KiB; floating-point numbers are not accepted.")
    metadata_digest: Annotated[str, Field(strict=True)]
    payment_required: Optional[Any] = Field(description="Complete immutable x402 v2 PAYMENT-REQUIRED document.")
    payment_required_header: StrictStr = Field(description="Canonical base64-encoded value to return in the buyer-facing PAYMENT-REQUIRED header.")
    eligible_alternatives: List[PublicNetworkFeeAlternative]
    fee_policy: PublicFeePolicyDocument
    fee_quote_digest: Annotated[str, Field(strict=True)]
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["charge_id", "charge_digest", "order_id", "status", "resource_version_id", "payment_identifier", "expires_at", "created_at", "prices", "requested_expires_in_seconds", "metadata", "metadata_digest", "payment_required", "payment_required_header", "eligible_alternatives", "fee_policy", "fee_quote_digest"]

    @field_validator('charge_digest', mode="before")
    def charge_digest_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if isinstance(value, str) and not re.match(r"^sha256:[0-9a-f]{64}$", value):
            raise ValueError(r"must validate the regular expression /^sha256:[0-9a-f]{64}$/")
        return value

    @field_validator('metadata_digest', mode="before")
    def metadata_digest_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if isinstance(value, str) and not re.match(r"^sha256:[0-9a-f]{64}$", value):
            raise ValueError(r"must validate the regular expression /^sha256:[0-9a-f]{64}$/")
        return value

    @field_validator('fee_quote_digest', mode="before")
    def fee_quote_digest_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if isinstance(value, str) and not re.match(r"^sha256:[0-9a-f]{64}$", value):
            raise ValueError(r"must validate the regular expression /^sha256:[0-9a-f]{64}$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DynamicChargeResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in prices (list)
        _items = []
        if self.prices:
            for _item_prices in self.prices:
                if _item_prices:
                    _items.append(_item_prices.to_dict())
            _dict['prices'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in eligible_alternatives (list)
        _items = []
        if self.eligible_alternatives:
            for _item_eligible_alternatives in self.eligible_alternatives:
                if _item_eligible_alternatives:
                    _items.append(_item_eligible_alternatives.to_dict())
            _dict['eligible_alternatives'] = _items
        # override the default output from pydantic by calling `to_dict()` of fee_policy
        if self.fee_policy:
            _dict['fee_policy'] = self.fee_policy.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if payment_required (nullable) is None
        # and model_fields_set contains the field
        if self.payment_required is None and "payment_required" in self.model_fields_set:
            _dict['payment_required'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DynamicChargeResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "charge_id": obj.get("charge_id"),
            "charge_digest": obj.get("charge_digest"),
            "order_id": obj.get("order_id"),
            "status": obj.get("status"),
            "resource_version_id": obj.get("resource_version_id"),
            "payment_identifier": obj.get("payment_identifier"),
            "expires_at": obj.get("expires_at"),
            "created_at": obj.get("created_at"),
            "prices": [DynamicChargePrice.from_dict(_item) for _item in obj["prices"]] if obj.get("prices") is not None else None,
            "requested_expires_in_seconds": obj.get("requested_expires_in_seconds"),
            "metadata": obj.get("metadata"),
            "metadata_digest": obj.get("metadata_digest"),
            "payment_required": obj.get("payment_required"),
            "payment_required_header": obj.get("payment_required_header"),
            "eligible_alternatives": [PublicNetworkFeeAlternative.from_dict(_item) for _item in obj["eligible_alternatives"]] if obj.get("eligible_alternatives") is not None else None,
            "fee_policy": PublicFeePolicyDocument.from_dict(obj["fee_policy"]) if obj.get("fee_policy") is not None else None,
            "fee_quote_digest": obj.get("fee_quote_digest")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
