# coding: utf-8

"""
    x402api Public API

    Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from x402api.models.dynamic_charge_price import DynamicChargePrice
from x402api.models.fee_policy_mode_input_enum import FeePolicyModeInputEnum
from x402api.models.fee_policy_quote_currency_input_enum import FeePolicyQuoteCurrencyInputEnum
from x402api.models.http_method_enum import HTTPMethodEnum
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DynamicChargeCreate(BaseModel):
    """
    DynamicChargeCreate
    """ # noqa: E501
    resource_version_id: UUID = Field(description="Current active resource-version UUID used as the charge template. Read resources[].active_version.id from GET /v1/resources or copy Active version UUID (charge API) in the tenant dashboard. Do not use the top-level resource id or pay_ public_payment_id.")
    method: Optional[HTTPMethodEnum] = None
    resource_url: Annotated[str, Field(strict=True, max_length=2048)]
    body_base64: Optional[Annotated[str, Field(strict=True, max_length=1400000)]] = ''
    content_type: Optional[Annotated[str, Field(strict=True, max_length=160)]] = None
    description: Optional[Annotated[str, Field(strict=True, max_length=500)]] = None
    prices: List[DynamicChargePrice]
    fee_mode: Optional[FeePolicyModeInputEnum] = None
    quote_currency: Optional[FeePolicyQuoteCurrencyInputEnum] = None
    fee_allowance_cap_quote_micros: Optional[Annotated[str, Field(strict=True, max_length=78)]] = None
    expires_in_seconds: Annotated[int, Field(le=3600, strict=True, ge=30)]
    metadata: Optional[Dict[str, Any]] = Field(default=None, description="Tenant application metadata frozen into the charge digest. Maximum canonical size is 16 KiB; floating-point numbers are not accepted.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["resource_version_id", "method", "resource_url", "body_base64", "content_type", "description", "prices", "fee_mode", "quote_currency", "fee_allowance_cap_quote_micros", "expires_in_seconds", "metadata"]

    @field_validator('fee_allowance_cap_quote_micros', mode="before")
    def fee_allowance_cap_quote_micros_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^(0|[1-9][0-9]*)$", value):
            raise ValueError(r"must validate the regular expression /^(0|[1-9][0-9]*)$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DynamicChargeCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in prices (list)
        _items = []
        if self.prices:
            for _item_prices in self.prices:
                if _item_prices:
                    _items.append(_item_prices.to_dict())
            _dict['prices'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if content_type (nullable) is None
        # and model_fields_set contains the field
        if self.content_type is None and "content_type" in self.model_fields_set:
            _dict['content_type'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DynamicChargeCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "resource_version_id": obj.get("resource_version_id"),
            "method": obj.get("method"),
            "resource_url": obj.get("resource_url"),
            "body_base64": obj.get("body_base64") if obj.get("body_base64") is not None else '',
            "content_type": obj.get("content_type"),
            "description": obj.get("description"),
            "prices": [DynamicChargePrice.from_dict(_item) for _item in obj["prices"]] if obj.get("prices") is not None else None,
            "fee_mode": obj.get("fee_mode"),
            "quote_currency": obj.get("quote_currency"),
            "fee_allowance_cap_quote_micros": obj.get("fee_allowance_cap_quote_micros"),
            "expires_in_seconds": obj.get("expires_in_seconds"),
            "metadata": obj.get("metadata")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
