# coding: utf-8

"""
    x402api Public API

    Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

    The version of the OpenAPI document: 1.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from x402api.models.external_address_proof_input_method_enum import ExternalAddressProofInputMethodEnum
from x402api.models.readiness_status_enum import ReadinessStatusEnum
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ExternalReceivingAddress(BaseModel):
    """
    ExternalReceivingAddress
    """ # noqa: E501
    id: UUID
    wallet_id: UUID
    wallet_version_id: UUID
    label: StrictStr
    network: StrictStr
    asset_id: StrictStr
    address: StrictStr
    status: StrictStr
    proof_method: Optional[ExternalAddressProofInputMethodEnum]
    proof_verified_at: Optional[datetime]
    readiness_state: StrictStr
    readiness_usable: StrictBool
    readiness_refresh_eligible: StrictBool
    readiness_status: ReadinessStatusEnum
    activation_eligible: StrictBool
    activation_eligible_at: datetime
    verified_at: datetime
    expires_at: datetime
    activated_at: Optional[datetime]
    observed_balance_atomic: Optional[StrictStr]
    created_at: datetime
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "wallet_id", "wallet_version_id", "label", "network", "asset_id", "address", "status", "proof_method", "proof_verified_at", "readiness_state", "readiness_usable", "readiness_refresh_eligible", "readiness_status", "activation_eligible", "activation_eligible_at", "verified_at", "expires_at", "activated_at", "observed_balance_atomic", "created_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExternalReceivingAddress from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "id",
            "wallet_id",
            "wallet_version_id",
            "label",
            "network",
            "asset_id",
            "address",
            "status",
            "proof_method",
            "proof_verified_at",
            "readiness_state",
            "readiness_usable",
            "readiness_refresh_eligible",
            "readiness_status",
            "activation_eligible",
            "activation_eligible_at",
            "verified_at",
            "expires_at",
            "activated_at",
            "observed_balance_atomic",
            "created_at",
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if proof_method (nullable) is None
        # and model_fields_set contains the field
        if self.proof_method is None and "proof_method" in self.model_fields_set:
            _dict['proof_method'] = None

        # set to None if proof_verified_at (nullable) is None
        # and model_fields_set contains the field
        if self.proof_verified_at is None and "proof_verified_at" in self.model_fields_set:
            _dict['proof_verified_at'] = None

        # set to None if activated_at (nullable) is None
        # and model_fields_set contains the field
        if self.activated_at is None and "activated_at" in self.model_fields_set:
            _dict['activated_at'] = None

        # set to None if observed_balance_atomic (nullable) is None
        # and model_fields_set contains the field
        if self.observed_balance_atomic is None and "observed_balance_atomic" in self.model_fields_set:
            _dict['observed_balance_atomic'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExternalReceivingAddress from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "wallet_id": obj.get("wallet_id"),
            "wallet_version_id": obj.get("wallet_version_id"),
            "label": obj.get("label"),
            "network": obj.get("network"),
            "asset_id": obj.get("asset_id"),
            "address": obj.get("address"),
            "status": obj.get("status"),
            "proof_method": obj.get("proof_method"),
            "proof_verified_at": obj.get("proof_verified_at"),
            "readiness_state": obj.get("readiness_state"),
            "readiness_usable": obj.get("readiness_usable"),
            "readiness_refresh_eligible": obj.get("readiness_refresh_eligible"),
            "readiness_status": obj.get("readiness_status"),
            "activation_eligible": obj.get("activation_eligible"),
            "activation_eligible_at": obj.get("activation_eligible_at"),
            "verified_at": obj.get("verified_at"),
            "expires_at": obj.get("expires_at"),
            "activated_at": obj.get("activated_at"),
            "observed_balance_atomic": obj.get("observed_balance_atomic"),
            "created_at": obj.get("created_at")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
