# coding: utf-8

"""
    x402api Public API

    Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

    The version of the OpenAPI document: 1.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ExternalAddressProofMethodEnum(str, Enum):
    """
    * `signed_message` - Signed message * `onchain_canary` - On-chain canary
    """

    """
    allowed enum values
    """
    SIGNED_MESSAGE = 'signed_message'
    ONCHAIN_CANARY = 'onchain_canary'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ExternalAddressProofMethodEnum from a JSON string"""
        return cls(json.loads(json_str))
