# coding: utf-8

"""
    x402api Public API

    Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from x402api.models.fee_policy_mode_input_enum import FeePolicyModeInputEnum
from x402api.models.fee_policy_quote_currency_input_enum import FeePolicyQuoteCurrencyInputEnum
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class FeePolicyDocument(BaseModel):
    """
    FeePolicyDocument
    """ # noqa: E501
    type: StrictStr
    version: Annotated[int, Field(strict=True, ge=1)]
    fee_mode: FeePolicyModeInputEnum = Field(alias="feeMode")
    quote_currency: FeePolicyQuoteCurrencyInputEnum = Field(alias="quoteCurrency")
    fee_allowance_cap_quote_micros: Annotated[str, Field(strict=True, max_length=78)] = Field(alias="feeAllowanceCapQuoteMicros")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["type", "version", "feeMode", "quoteCurrency", "feeAllowanceCapQuoteMicros"]

    @field_validator('fee_allowance_cap_quote_micros', mode="before")
    def fee_allowance_cap_quote_micros_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if isinstance(value, str) and not re.match(r"^(0|[1-9][0-9]*)$", value):
            raise ValueError(r"must validate the regular expression /^(0|[1-9][0-9]*)$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FeePolicyDocument from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FeePolicyDocument from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "version": obj.get("version"),
            "feeMode": obj.get("feeMode"),
            "quoteCurrency": obj.get("quoteCurrency"),
            "feeAllowanceCapQuoteMicros": obj.get("feeAllowanceCapQuoteMicros")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
