# coding: utf-8

"""
    x402api Public API

    Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class FeePolicyModeInputEnum(str, Enum):
    """
    * `buyer_pays` - buyer_pays * `tenant_absorbs_up_to_cap` - tenant_absorbs_up_to_cap
    """

    """
    allowed enum values
    """
    BUYER_PAYS = 'buyer_pays'
    TENANT_ABSORBS_UP_TO_CAP = 'tenant_absorbs_up_to_cap'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FeePolicyModeInputEnum from a JSON string"""
        return cls(json.loads(json_str))
