# coding: utf-8

"""
    x402api Public API

    Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class GasModeEnum(str, Enum):
    """
    * `buyer_pays` - buyer_pays * `sponsored` - sponsored
    """

    """
    allowed enum values
    """
    BUYER_PAYS = 'buyer_pays'
    SPONSORED = 'sponsored'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GasModeEnum from a JSON string"""
        return cls(json.loads(json_str))
