# coding: utf-8

"""
    x402api Public API

    Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

    The version of the OpenAPI document: 1.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class IdempotencyOutcomeStateEnum(str, Enum):
    """
    * `absent` - absent * `in_progress` - in_progress * `completed` - completed
    """

    """
    allowed enum values
    """
    ABSENT = 'absent'
    IN_PROGRESS = 'in_progress'
    COMPLETED = 'completed'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of IdempotencyOutcomeStateEnum from a JSON string"""
        return cls(json.loads(json_str))
