# coding: utf-8

"""
    x402api Public API

    Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class OrderStatusEnum(str, Enum):
    """
    * `created` - Created * `payment_pending` - Payment pending * `paid` - Paid * `fulfillment_pending` - Fulfillment pending * `fulfilled` - Fulfilled * `expired` - Expired * `failed` - Failed
    """

    """
    allowed enum values
    """
    CREATED = 'created'
    PAYMENT_PENDING = 'payment_pending'
    PAID = 'paid'
    FULFILLMENT_PENDING = 'fulfillment_pending'
    FULFILLED = 'fulfilled'
    EXPIRED = 'expired'
    FAILED = 'failed'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OrderStatusEnum from a JSON string"""
        return cls(json.loads(json_str))
