# coding: utf-8

"""
    x402api Public API

    Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PaymentReadinessRailStatusEnum(str, Enum):
    """
    * `ready` - ready * `needs_wallet` - needs_wallet * `paused_by_tenant` - paused_by_tenant * `temporarily_unavailable` - temporarily_unavailable * `not_selected` - not_selected
    """

    """
    allowed enum values
    """
    READY = 'ready'
    NEEDS_WALLET = 'needs_wallet'
    PAUSED_BY_TENANT = 'paused_by_tenant'
    TEMPORARILY_UNAVAILABLE = 'temporarily_unavailable'
    NOT_SELECTED = 'not_selected'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PaymentReadinessRailStatusEnum from a JSON string"""
        return cls(json.loads(json_str))
