# coding: utf-8

"""
    x402api Public API

    Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from x402api.models.fee_policy_document import FeePolicyDocument
from x402api.models.network_fee_alternative import NetworkFeeAlternative
from x402api.models.network_fee_evidence import NetworkFeeEvidence
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PaymentReceipt(BaseModel):
    """
    PaymentReceipt
    """ # noqa: E501
    id: UUID
    order_id: UUID
    settlement_job_id: UUID
    receipt: Optional[Any]
    receipt_digest: StrictStr
    signature: StrictStr
    signing_key_version: StrictStr
    eligible_alternatives: List[NetworkFeeAlternative]
    fee_policy: Optional[FeePolicyDocument]
    fee_evidence: Optional[NetworkFeeEvidence]
    fee_quote_digest: Optional[StrictStr]
    fee_quote_expires_at: Optional[datetime]
    settlement_amount_atomic: StrictStr
    created_at: datetime
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "order_id", "settlement_job_id", "receipt", "receipt_digest", "signature", "signing_key_version", "eligible_alternatives", "fee_policy", "fee_evidence", "fee_quote_digest", "fee_quote_expires_at", "settlement_amount_atomic", "created_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaymentReceipt from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "id",
            "order_id",
            "settlement_job_id",
            "receipt",
            "receipt_digest",
            "signature",
            "signing_key_version",
            "eligible_alternatives",
            "fee_policy",
            "fee_evidence",
            "fee_quote_digest",
            "fee_quote_expires_at",
            "settlement_amount_atomic",
            "created_at",
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in eligible_alternatives (list)
        _items = []
        if self.eligible_alternatives:
            for _item_eligible_alternatives in self.eligible_alternatives:
                if _item_eligible_alternatives:
                    _items.append(_item_eligible_alternatives.to_dict())
            _dict['eligible_alternatives'] = _items
        # override the default output from pydantic by calling `to_dict()` of fee_policy
        if self.fee_policy:
            _dict['fee_policy'] = self.fee_policy.to_dict()
        # override the default output from pydantic by calling `to_dict()` of fee_evidence
        if self.fee_evidence:
            _dict['fee_evidence'] = self.fee_evidence.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if receipt (nullable) is None
        # and model_fields_set contains the field
        if self.receipt is None and "receipt" in self.model_fields_set:
            _dict['receipt'] = None

        # set to None if fee_policy (nullable) is None
        # and model_fields_set contains the field
        if self.fee_policy is None and "fee_policy" in self.model_fields_set:
            _dict['fee_policy'] = None

        # set to None if fee_evidence (nullable) is None
        # and model_fields_set contains the field
        if self.fee_evidence is None and "fee_evidence" in self.model_fields_set:
            _dict['fee_evidence'] = None

        # set to None if fee_quote_digest (nullable) is None
        # and model_fields_set contains the field
        if self.fee_quote_digest is None and "fee_quote_digest" in self.model_fields_set:
            _dict['fee_quote_digest'] = None

        # set to None if fee_quote_expires_at (nullable) is None
        # and model_fields_set contains the field
        if self.fee_quote_expires_at is None and "fee_quote_expires_at" in self.model_fields_set:
            _dict['fee_quote_expires_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaymentReceipt from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "order_id": obj.get("order_id"),
            "settlement_job_id": obj.get("settlement_job_id"),
            "receipt": obj.get("receipt"),
            "receipt_digest": obj.get("receipt_digest"),
            "signature": obj.get("signature"),
            "signing_key_version": obj.get("signing_key_version"),
            "eligible_alternatives": [NetworkFeeAlternative.from_dict(_item) for _item in obj["eligible_alternatives"]] if obj.get("eligible_alternatives") is not None else None,
            "fee_policy": FeePolicyDocument.from_dict(obj["fee_policy"]) if obj.get("fee_policy") is not None else None,
            "fee_evidence": NetworkFeeEvidence.from_dict(obj["fee_evidence"]) if obj.get("fee_evidence") is not None else None,
            "fee_quote_digest": obj.get("fee_quote_digest"),
            "fee_quote_expires_at": obj.get("fee_quote_expires_at"),
            "settlement_amount_atomic": obj.get("settlement_amount_atomic"),
            "created_at": obj.get("created_at")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
