# coding: utf-8

"""
    x402api Public API

    Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

    The version of the OpenAPI document: 1.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PaymentReadinessStateEnum(str, Enum):
    """
    * `accepting` - accepting * `setup_required` - setup_required * `temporarily_unavailable` - temporarily_unavailable * `paused_by_tenant` - paused_by_tenant
    """

    """
    allowed enum values
    """
    ACCEPTING = 'accepting'
    SETUP_REQUIRED = 'setup_required'
    TEMPORARILY_UNAVAILABLE = 'temporarily_unavailable'
    PAUSED_BY_TENANT = 'paused_by_tenant'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PaymentReadinessStateEnum from a JSON string"""
        return cls(json.loads(json_str))
