# coding: utf-8

"""
    x402api Public API

    Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from x402api.models.payment_readiness_rail import PaymentReadinessRail
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PaymentReadiness(BaseModel):
    """
    PaymentReadiness
    """ # noqa: E501
    observed_at: datetime
    tenant_status: StrictStr
    tenant_accepting_new_challenges: StrictBool
    global_challenges_enabled: StrictBool
    global_settlement_enabled: StrictBool
    control_plane_ready_for_new_challenges: StrictBool
    control_plane_ready_for_settlement: StrictBool
    external_onboarding: Optional[Any]
    rails: List[PaymentReadinessRail]
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["observed_at", "tenant_status", "tenant_accepting_new_challenges", "global_challenges_enabled", "global_settlement_enabled", "control_plane_ready_for_new_challenges", "control_plane_ready_for_settlement", "external_onboarding", "rails"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaymentReadiness from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "observed_at",
            "tenant_status",
            "tenant_accepting_new_challenges",
            "global_challenges_enabled",
            "global_settlement_enabled",
            "control_plane_ready_for_new_challenges",
            "control_plane_ready_for_settlement",
            "external_onboarding",
            "rails",
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in rails (list)
        _items = []
        if self.rails:
            for _item_rails in self.rails:
                if _item_rails:
                    _items.append(_item_rails.to_dict())
            _dict['rails'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if external_onboarding (nullable) is None
        # and model_fields_set contains the field
        if self.external_onboarding is None and "external_onboarding" in self.model_fields_set:
            _dict['external_onboarding'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaymentReadiness from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "observed_at": obj.get("observed_at"),
            "tenant_status": obj.get("tenant_status"),
            "tenant_accepting_new_challenges": obj.get("tenant_accepting_new_challenges"),
            "global_challenges_enabled": obj.get("global_challenges_enabled"),
            "global_settlement_enabled": obj.get("global_settlement_enabled"),
            "control_plane_ready_for_new_challenges": obj.get("control_plane_ready_for_new_challenges"),
            "control_plane_ready_for_settlement": obj.get("control_plane_ready_for_settlement"),
            "external_onboarding": obj.get("external_onboarding"),
            "rails": [PaymentReadinessRail.from_dict(_item) for _item in obj["rails"]] if obj.get("rails") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
