# coding: utf-8

"""
    x402api Public API

    Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

    The version of the OpenAPI document: 1.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from x402api.models.gas_mode_enum import GasModeEnum
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PublicNetworkFeeAlternative(BaseModel):
    """
    PublicNetworkFeeAlternative
    """ # noqa: E501
    type: StrictStr
    version: Annotated[int, Field(strict=True, ge=1)]
    network: Annotated[str, Field(strict=True, max_length=80)]
    asset_id: Annotated[str, Field(strict=True, max_length=80)] = Field(alias="assetId")
    contract_address: Annotated[str, Field(strict=True, max_length=160)] = Field(alias="contractAddress")
    listed_amount_atomic: Annotated[str, Field(strict=True, max_length=78)] = Field(alias="listedAmountAtomic")
    gas_mode: GasModeEnum = Field(alias="gasMode")
    buyer_native_fee_atomic: Optional[Annotated[str, Field(strict=True, max_length=78)]] = Field(alias="buyerNativeFeeAtomic")
    buyer_payment_atomic: Annotated[str, Field(strict=True, max_length=78)] = Field(alias="buyerPaymentAtomic")
    tenant_proceeds_atomic: Annotated[str, Field(strict=True, max_length=78)] = Field(alias="tenantProceedsAtomic")
    quote_expires_at: Optional[datetime] = Field(alias="quoteExpiresAt")
    eligible: StrictBool
    exclusion_reason: Optional[Annotated[str, Field(strict=True, max_length=80)]] = Field(alias="exclusionReason")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["type", "version", "network", "assetId", "contractAddress", "listedAmountAtomic", "gasMode", "buyerNativeFeeAtomic", "buyerPaymentAtomic", "tenantProceedsAtomic", "quoteExpiresAt", "eligible", "exclusionReason"]

    @field_validator('asset_id', mode="before")
    def asset_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if isinstance(value, str) and not re.match(r"^[-a-zA-Z0-9_]+$", value):
            raise ValueError(r"must validate the regular expression /^[-a-zA-Z0-9_]+$/")
        return value

    @field_validator('listed_amount_atomic', mode="before")
    def listed_amount_atomic_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if isinstance(value, str) and not re.match(r"^[1-9][0-9]*$", value):
            raise ValueError(r"must validate the regular expression /^[1-9][0-9]*$/")
        return value

    @field_validator('buyer_native_fee_atomic', mode="before")
    def buyer_native_fee_atomic_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^(0|[1-9][0-9]*)$", value):
            raise ValueError(r"must validate the regular expression /^(0|[1-9][0-9]*)$/")
        return value

    @field_validator('buyer_payment_atomic', mode="before")
    def buyer_payment_atomic_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if isinstance(value, str) and not re.match(r"^(0|[1-9][0-9]*)$", value):
            raise ValueError(r"must validate the regular expression /^(0|[1-9][0-9]*)$/")
        return value

    @field_validator('tenant_proceeds_atomic', mode="before")
    def tenant_proceeds_atomic_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if isinstance(value, str) and not re.match(r"^(0|[1-9][0-9]*)$", value):
            raise ValueError(r"must validate the regular expression /^(0|[1-9][0-9]*)$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PublicNetworkFeeAlternative from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if buyer_native_fee_atomic (nullable) is None
        # and model_fields_set contains the field
        if self.buyer_native_fee_atomic is None and "buyer_native_fee_atomic" in self.model_fields_set:
            _dict['buyerNativeFeeAtomic'] = None

        # set to None if quote_expires_at (nullable) is None
        # and model_fields_set contains the field
        if self.quote_expires_at is None and "quote_expires_at" in self.model_fields_set:
            _dict['quoteExpiresAt'] = None

        # set to None if exclusion_reason (nullable) is None
        # and model_fields_set contains the field
        if self.exclusion_reason is None and "exclusion_reason" in self.model_fields_set:
            _dict['exclusionReason'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PublicNetworkFeeAlternative from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "version": obj.get("version"),
            "network": obj.get("network"),
            "assetId": obj.get("assetId"),
            "contractAddress": obj.get("contractAddress"),
            "listedAmountAtomic": obj.get("listedAmountAtomic"),
            "gasMode": obj.get("gasMode"),
            "buyerNativeFeeAtomic": obj.get("buyerNativeFeeAtomic"),
            "buyerPaymentAtomic": obj.get("buyerPaymentAtomic"),
            "tenantProceedsAtomic": obj.get("tenantProceedsAtomic"),
            "quoteExpiresAt": obj.get("quoteExpiresAt"),
            "eligible": obj.get("eligible"),
            "exclusionReason": obj.get("exclusionReason")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
