# coding: utf-8

"""
    x402api Public API

    Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

    The version of the OpenAPI document: 1.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ReceiptStatusEnum(str, Enum):
    """
    * `pending_confirmation` - pending_confirmation * `pending_finality` - pending_finality
    """

    """
    allowed enum values
    """
    PENDING_CONFIRMATION = 'pending_confirmation'
    PENDING_FINALITY = 'pending_finality'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ReceiptStatusEnum from a JSON string"""
        return cls(json.loads(json_str))
