# coding: utf-8

"""
    x402api Public API

    Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from x402api.models.fee_policy_mode_input_enum import FeePolicyModeInputEnum
from x402api.models.fee_policy_quote_currency_input_enum import FeePolicyQuoteCurrencyInputEnum
from x402api.models.http_method_enum import HTTPMethodEnum
from x402api.models.price_input import PriceInput
from x402api.models.resource_create_fulfillment_config import ResourceCreateFulfillmentConfig
from x402api.models.resource_input_fulfillment_mode_enum import ResourceInputFulfillmentModeEnum
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ResourceCreate(BaseModel):
    """
    ResourceCreate
    """ # noqa: E501
    fee_mode: Optional[FeePolicyModeInputEnum] = None
    quote_currency: Optional[FeePolicyQuoteCurrencyInputEnum] = None
    fee_allowance_cap_quote_micros: Optional[Annotated[str, Field(strict=True, max_length=78)]] = '0'
    key: Annotated[str, Field(strict=True, max_length=120)]
    name: Annotated[str, Field(strict=True, max_length=160)]
    method: HTTPMethodEnum
    path: Annotated[str, Field(strict=True, max_length=1024)]
    description: Annotated[str, Field(strict=True, max_length=500)]
    mime_type: Optional[Annotated[str, Field(strict=True, max_length=160)]] = 'application/json'
    fulfillment_mode: ResourceInputFulfillmentModeEnum
    fulfillment_config: Optional[ResourceCreateFulfillmentConfig] = None
    prices: List[PriceInput]
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["fee_mode", "quote_currency", "fee_allowance_cap_quote_micros", "key", "name", "method", "path", "description", "mime_type", "fulfillment_mode", "fulfillment_config", "prices"]

    @field_validator('fee_allowance_cap_quote_micros', mode="before")
    def fee_allowance_cap_quote_micros_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^(0|[1-9][0-9]*)$", value):
            raise ValueError(r"must validate the regular expression /^(0|[1-9][0-9]*)$/")
        return value

    @field_validator('key', mode="before")
    def key_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if isinstance(value, str) and not re.match(r"^[-a-zA-Z0-9_]+$", value):
            raise ValueError(r"must validate the regular expression /^[-a-zA-Z0-9_]+$/")
        return value

    @field_validator('path', mode="before")
    def path_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if isinstance(value, str) and not re.match(r"^\/[^\s?#]*$", value):
            raise ValueError(r"must validate the regular expression /^\/[^\s?#]*$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ResourceCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of fulfillment_config
        if self.fulfillment_config:
            _dict['fulfillment_config'] = self.fulfillment_config.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in prices (list)
        _items = []
        if self.prices:
            for _item_prices in self.prices:
                if _item_prices:
                    _items.append(_item_prices.to_dict())
            _dict['prices'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ResourceCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "fee_mode": obj.get("fee_mode"),
            "quote_currency": obj.get("quote_currency"),
            "fee_allowance_cap_quote_micros": obj.get("fee_allowance_cap_quote_micros") if obj.get("fee_allowance_cap_quote_micros") is not None else '0',
            "key": obj.get("key"),
            "name": obj.get("name"),
            "method": obj.get("method"),
            "path": obj.get("path"),
            "description": obj.get("description"),
            "mime_type": obj.get("mime_type") if obj.get("mime_type") is not None else 'application/json',
            "fulfillment_mode": obj.get("fulfillment_mode"),
            "fulfillment_config": ResourceCreateFulfillmentConfig.from_dict(obj["fulfillment_config"]) if obj.get("fulfillment_config") is not None else None,
            "prices": [PriceInput.from_dict(_item) for _item in obj["prices"]] if obj.get("prices") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
