# coding: utf-8

"""
    x402api Public API

    Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from uuid import UUID
from x402api.models.resource_fee_mode_enum import ResourceFeeModeEnum
from x402api.models.resource_price import ResourcePrice
from x402api.models.resource_quote_currency_enum import ResourceQuoteCurrencyEnum
from x402api.models.resource_version_fulfillment_config import ResourceVersionFulfillmentConfig
from x402api.models.resource_version_fulfillment_mode_enum import ResourceVersionFulfillmentModeEnum
from x402api.models.resource_version_state_enum import ResourceVersionStateEnum
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ResourceVersion(BaseModel):
    """
    ResourceVersion
    """ # noqa: E501
    id: UUID
    version: StrictInt
    method: StrictStr
    path: StrictStr
    description: StrictStr
    mime_type: StrictStr
    fulfillment_mode: ResourceVersionFulfillmentModeEnum
    fulfillment_config: ResourceVersionFulfillmentConfig
    fee_mode: ResourceFeeModeEnum
    quote_currency: ResourceQuoteCurrencyEnum
    fee_allowance_cap_quote_micros: StrictStr
    state: ResourceVersionStateEnum
    prices: List[ResourcePrice]
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "version", "method", "path", "description", "mime_type", "fulfillment_mode", "fulfillment_config", "fee_mode", "quote_currency", "fee_allowance_cap_quote_micros", "state", "prices"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ResourceVersion from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "id",
            "version",
            "method",
            "path",
            "description",
            "mime_type",
            "fulfillment_mode",
            "fee_mode",
            "quote_currency",
            "fee_allowance_cap_quote_micros",
            "state",
            "prices",
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of fulfillment_config
        if self.fulfillment_config:
            _dict['fulfillment_config'] = self.fulfillment_config.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in prices (list)
        _items = []
        if self.prices:
            for _item_prices in self.prices:
                if _item_prices:
                    _items.append(_item_prices.to_dict())
            _dict['prices'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ResourceVersion from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "version": obj.get("version"),
            "method": obj.get("method"),
            "path": obj.get("path"),
            "description": obj.get("description"),
            "mime_type": obj.get("mime_type"),
            "fulfillment_mode": obj.get("fulfillment_mode"),
            "fulfillment_config": ResourceVersionFulfillmentConfig.from_dict(obj["fulfillment_config"]) if obj.get("fulfillment_config") is not None else None,
            "fee_mode": obj.get("fee_mode"),
            "quote_currency": obj.get("quote_currency"),
            "fee_allowance_cap_quote_micros": obj.get("fee_allowance_cap_quote_micros"),
            "state": obj.get("state"),
            "prices": [ResourcePrice.from_dict(_item) for _item in obj["prices"]] if obj.get("prices") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
