# coding: utf-8

"""
    x402api Public API

    Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from x402api.models.settlement_job_state_enum import SettlementJobStateEnum
from x402api.models.tenant_payment_asset_projection import TenantPaymentAssetProjection
from x402api.models.tenant_payment_chain_projection import TenantPaymentChainProjection
from x402api.models.tenant_payment_fulfillment_projection import TenantPaymentFulfillmentProjection
from x402api.models.tenant_payment_order_projection import TenantPaymentOrderProjection
from x402api.models.tenant_payment_receipt_projection import TenantPaymentReceiptProjection
from x402api.models.tenant_payment_resource_projection import TenantPaymentResourceProjection
from x402api.models.tenant_payment_screening_projection import TenantPaymentScreeningProjection
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SettlementJob(BaseModel):
    """
    SettlementJob
    """ # noqa: E501
    id: UUID
    order_id: UUID
    reservation_id: UUID
    state: SettlementJobStateEnum
    network: StrictStr
    transaction_hash: StrictStr
    original_transaction_hash: StrictStr
    replaced_by_hash: StrictStr
    gas_execution_state: StrictStr
    gas_execution_sequence: StrictInt
    gas_execution_material_digest: StrictStr
    gas_execution_observed_at: Optional[datetime]
    payer: StrictStr
    last_error_code: StrictStr
    broadcast_attempt_count: StrictInt
    settlement_result: Optional[Any]
    confirmed_at: Optional[datetime]
    finalized_at: Optional[datetime]
    created_at: datetime
    updated_at: datetime
    order: TenantPaymentOrderProjection
    resource: TenantPaymentResourceProjection
    asset: TenantPaymentAssetProjection
    chain: TenantPaymentChainProjection
    receipt: TenantPaymentReceiptProjection
    screening: TenantPaymentScreeningProjection
    fulfillment: TenantPaymentFulfillmentProjection
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "order_id", "reservation_id", "state", "network", "transaction_hash", "original_transaction_hash", "replaced_by_hash", "gas_execution_state", "gas_execution_sequence", "gas_execution_material_digest", "gas_execution_observed_at", "payer", "last_error_code", "broadcast_attempt_count", "settlement_result", "confirmed_at", "finalized_at", "created_at", "updated_at", "order", "resource", "asset", "chain", "receipt", "screening", "fulfillment"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SettlementJob from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "id",
            "order_id",
            "reservation_id",
            "state",
            "network",
            "transaction_hash",
            "original_transaction_hash",
            "replaced_by_hash",
            "gas_execution_state",
            "gas_execution_sequence",
            "gas_execution_material_digest",
            "gas_execution_observed_at",
            "payer",
            "last_error_code",
            "broadcast_attempt_count",
            "settlement_result",
            "confirmed_at",
            "finalized_at",
            "created_at",
            "updated_at",
            "order",
            "resource",
            "asset",
            "chain",
            "receipt",
            "screening",
            "fulfillment",
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of order
        if self.order:
            _dict['order'] = self.order.to_dict()
        # override the default output from pydantic by calling `to_dict()` of resource
        if self.resource:
            _dict['resource'] = self.resource.to_dict()
        # override the default output from pydantic by calling `to_dict()` of asset
        if self.asset:
            _dict['asset'] = self.asset.to_dict()
        # override the default output from pydantic by calling `to_dict()` of chain
        if self.chain:
            _dict['chain'] = self.chain.to_dict()
        # override the default output from pydantic by calling `to_dict()` of receipt
        if self.receipt:
            _dict['receipt'] = self.receipt.to_dict()
        # override the default output from pydantic by calling `to_dict()` of screening
        if self.screening:
            _dict['screening'] = self.screening.to_dict()
        # override the default output from pydantic by calling `to_dict()` of fulfillment
        if self.fulfillment:
            _dict['fulfillment'] = self.fulfillment.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if gas_execution_observed_at (nullable) is None
        # and model_fields_set contains the field
        if self.gas_execution_observed_at is None and "gas_execution_observed_at" in self.model_fields_set:
            _dict['gas_execution_observed_at'] = None

        # set to None if settlement_result (nullable) is None
        # and model_fields_set contains the field
        if self.settlement_result is None and "settlement_result" in self.model_fields_set:
            _dict['settlement_result'] = None

        # set to None if confirmed_at (nullable) is None
        # and model_fields_set contains the field
        if self.confirmed_at is None and "confirmed_at" in self.model_fields_set:
            _dict['confirmed_at'] = None

        # set to None if finalized_at (nullable) is None
        # and model_fields_set contains the field
        if self.finalized_at is None and "finalized_at" in self.model_fields_set:
            _dict['finalized_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SettlementJob from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "order_id": obj.get("order_id"),
            "reservation_id": obj.get("reservation_id"),
            "state": obj.get("state"),
            "network": obj.get("network"),
            "transaction_hash": obj.get("transaction_hash"),
            "original_transaction_hash": obj.get("original_transaction_hash"),
            "replaced_by_hash": obj.get("replaced_by_hash"),
            "gas_execution_state": obj.get("gas_execution_state"),
            "gas_execution_sequence": obj.get("gas_execution_sequence"),
            "gas_execution_material_digest": obj.get("gas_execution_material_digest"),
            "gas_execution_observed_at": obj.get("gas_execution_observed_at"),
            "payer": obj.get("payer"),
            "last_error_code": obj.get("last_error_code"),
            "broadcast_attempt_count": obj.get("broadcast_attempt_count"),
            "settlement_result": obj.get("settlement_result"),
            "confirmed_at": obj.get("confirmed_at"),
            "finalized_at": obj.get("finalized_at"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "order": TenantPaymentOrderProjection.from_dict(obj["order"]) if obj.get("order") is not None else None,
            "resource": TenantPaymentResourceProjection.from_dict(obj["resource"]) if obj.get("resource") is not None else None,
            "asset": TenantPaymentAssetProjection.from_dict(obj["asset"]) if obj.get("asset") is not None else None,
            "chain": TenantPaymentChainProjection.from_dict(obj["chain"]) if obj.get("chain") is not None else None,
            "receipt": TenantPaymentReceiptProjection.from_dict(obj["receipt"]) if obj.get("receipt") is not None else None,
            "screening": TenantPaymentScreeningProjection.from_dict(obj["screening"]) if obj.get("screening") is not None else None,
            "fulfillment": TenantPaymentFulfillmentProjection.from_dict(obj["fulfillment"]) if obj.get("fulfillment") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
