# coding: utf-8

"""
    x402api Public API

    Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from x402api.models.settlement_chain_observation_state_enum import SettlementChainObservationStateEnum
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SettlementChainObservation(BaseModel):
    """
    SettlementChainObservation
    """ # noqa: E501
    id: UUID
    settlement_job_id: UUID
    network: StrictStr
    transaction_hash: StrictStr
    state: SettlementChainObservationStateEnum
    observation_digest: StrictStr
    log_index: Optional[StrictInt]
    block_number: Optional[Annotated[str, Field(strict=True)]]
    block_hash: StrictStr
    asset_contract: StrictStr
    payer: StrictStr
    recipient: StrictStr
    amount_atomic: Optional[Annotated[str, Field(strict=True)]]
    execution_success: Optional[StrictBool]
    observed_at: datetime
    created_at: datetime
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "settlement_job_id", "network", "transaction_hash", "state", "observation_digest", "log_index", "block_number", "block_hash", "asset_contract", "payer", "recipient", "amount_atomic", "execution_success", "observed_at", "created_at"]

    @field_validator('block_number', mode="before")
    def block_number_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^-?\d{0,78}(?:\.\d{0,0})?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d{0,78}(?:\.\d{0,0})?$/")
        return value

    @field_validator('amount_atomic', mode="before")
    def amount_atomic_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^-?\d{0,78}(?:\.\d{0,0})?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d{0,78}(?:\.\d{0,0})?$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SettlementChainObservation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "id",
            "settlement_job_id",
            "network",
            "transaction_hash",
            "state",
            "observation_digest",
            "log_index",
            "block_number",
            "block_hash",
            "asset_contract",
            "payer",
            "recipient",
            "amount_atomic",
            "execution_success",
            "observed_at",
            "created_at",
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if log_index (nullable) is None
        # and model_fields_set contains the field
        if self.log_index is None and "log_index" in self.model_fields_set:
            _dict['log_index'] = None

        # set to None if block_number (nullable) is None
        # and model_fields_set contains the field
        if self.block_number is None and "block_number" in self.model_fields_set:
            _dict['block_number'] = None

        # set to None if amount_atomic (nullable) is None
        # and model_fields_set contains the field
        if self.amount_atomic is None and "amount_atomic" in self.model_fields_set:
            _dict['amount_atomic'] = None

        # set to None if execution_success (nullable) is None
        # and model_fields_set contains the field
        if self.execution_success is None and "execution_success" in self.model_fields_set:
            _dict['execution_success'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SettlementChainObservation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "settlement_job_id": obj.get("settlement_job_id"),
            "network": obj.get("network"),
            "transaction_hash": obj.get("transaction_hash"),
            "state": obj.get("state"),
            "observation_digest": obj.get("observation_digest"),
            "log_index": obj.get("log_index"),
            "block_number": obj.get("block_number"),
            "block_hash": obj.get("block_hash"),
            "asset_contract": obj.get("asset_contract"),
            "payer": obj.get("payer"),
            "recipient": obj.get("recipient"),
            "amount_atomic": obj.get("amount_atomic"),
            "execution_success": obj.get("execution_success"),
            "observed_at": obj.get("observed_at"),
            "created_at": obj.get("created_at")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
