# coding: utf-8

"""
    x402api Public API

    Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class TenantPaymentReceiptProjectionStatusEnum(str, Enum):
    """
    * `not_issued` - not_issued * `issued` - issued * `integrity_failure` - integrity_failure
    """

    """
    allowed enum values
    """
    NOT_ISSUED = 'not_issued'
    ISSUED = 'issued'
    INTEGRITY_FAILURE = 'integrity_failure'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TenantPaymentReceiptProjectionStatusEnum from a JSON string"""
        return cls(json.loads(json_str))
