# coding: utf-8

"""
    x402api Public API

    Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class TenantPaymentScreeningSubjectProjectionStatusEnum(str, Enum):
    """
    * `not_enforced` - not_enforced * `allowed` - allowed * `not_allowed` - not_allowed * `unavailable` - unavailable
    """

    """
    allowed enum values
    """
    NOT_ENFORCED = 'not_enforced'
    ALLOWED = 'allowed'
    NOT_ALLOWED = 'not_allowed'
    UNAVAILABLE = 'unavailable'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TenantPaymentScreeningSubjectProjectionStatusEnum from a JSON string"""
        return cls(json.loads(json_str))
