# coding: utf-8

"""
    x402api Public API

    Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from x402api.models.balance_asset import BalanceAsset
from x402api.models.observation_state_enum import ObservationStateEnum
from x402api.models.wallet_chain_reseed_context import WalletChainReseedContext
from x402api.models.wallet_version_balance_state_enum import WalletVersionBalanceStateEnum
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class WalletVersionBalance(BaseModel):
    """
    WalletVersionBalance
    """ # noqa: E501
    wallet_version_id: UUID
    version: StrictInt
    wallet_address: StrictStr
    state: WalletVersionBalanceStateEnum
    observation_state: ObservationStateEnum
    observed_at: Optional[datetime]
    assets: List[BalanceAsset]
    reseed_context: Optional[WalletChainReseedContext]
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["wallet_version_id", "version", "wallet_address", "state", "observation_state", "observed_at", "assets", "reseed_context"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WalletVersionBalance from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in assets (list)
        _items = []
        if self.assets:
            for _item_assets in self.assets:
                if _item_assets:
                    _items.append(_item_assets.to_dict())
            _dict['assets'] = _items
        # override the default output from pydantic by calling `to_dict()` of reseed_context
        if self.reseed_context:
            _dict['reseed_context'] = self.reseed_context.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if observed_at (nullable) is None
        # and model_fields_set contains the field
        if self.observed_at is None and "observed_at" in self.model_fields_set:
            _dict['observed_at'] = None

        # set to None if reseed_context (nullable) is None
        # and model_fields_set contains the field
        if self.reseed_context is None and "reseed_context" in self.model_fields_set:
            _dict['reseed_context'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WalletVersionBalance from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "wallet_version_id": obj.get("wallet_version_id"),
            "version": obj.get("version"),
            "wallet_address": obj.get("wallet_address"),
            "state": obj.get("state"),
            "observation_state": obj.get("observation_state"),
            "observed_at": obj.get("observed_at"),
            "assets": [BalanceAsset.from_dict(_item) for _item in obj["assets"]] if obj.get("assets") is not None else None,
            "reseed_context": WalletChainReseedContext.from_dict(obj["reseed_context"]) if obj.get("reseed_context") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
