# coding: utf-8

"""
    x402api Public API

    Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

    The version of the OpenAPI document: 1.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from x402api.models.balance_asset import BalanceAsset
from x402api.models.observation_state_enum import ObservationStateEnum
from x402api.models.tracking_status_enum import TrackingStatusEnum
from x402api.models.wallet_fenced_chain_reseed_context import WalletFencedChainReseedContext
from x402api.models.wallet_observation_finality_enum import WalletObservationFinalityEnum
from x402api.models.wallet_version_balance import WalletVersionBalance
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class WalletBalanceResponse(BaseModel):
    """
    WalletBalanceResponse
    """ # noqa: E501
    wallet_id: UUID
    network: StrictStr
    wallet_address: Optional[StrictStr]
    requested_finality: WalletObservationFinalityEnum
    observation_state: ObservationStateEnum
    tracking_status: TrackingStatusEnum
    observed_at: Optional[datetime]
    assets: List[BalanceAsset]
    wallet_versions: List[WalletVersionBalance]
    reseed_contexts: List[WalletFencedChainReseedContext]
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["wallet_id", "network", "wallet_address", "requested_finality", "observation_state", "tracking_status", "observed_at", "assets", "wallet_versions", "reseed_contexts"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WalletBalanceResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in assets (list)
        _items = []
        if self.assets:
            for _item_assets in self.assets:
                if _item_assets:
                    _items.append(_item_assets.to_dict())
            _dict['assets'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in wallet_versions (list)
        _items = []
        if self.wallet_versions:
            for _item_wallet_versions in self.wallet_versions:
                if _item_wallet_versions:
                    _items.append(_item_wallet_versions.to_dict())
            _dict['wallet_versions'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in reseed_contexts (list)
        _items = []
        if self.reseed_contexts:
            for _item_reseed_contexts in self.reseed_contexts:
                if _item_reseed_contexts:
                    _items.append(_item_reseed_contexts.to_dict())
            _dict['reseed_contexts'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if wallet_address (nullable) is None
        # and model_fields_set contains the field
        if self.wallet_address is None and "wallet_address" in self.model_fields_set:
            _dict['wallet_address'] = None

        # set to None if observed_at (nullable) is None
        # and model_fields_set contains the field
        if self.observed_at is None and "observed_at" in self.model_fields_set:
            _dict['observed_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WalletBalanceResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "wallet_id": obj.get("wallet_id"),
            "network": obj.get("network"),
            "wallet_address": obj.get("wallet_address"),
            "requested_finality": obj.get("requested_finality"),
            "observation_state": obj.get("observation_state"),
            "tracking_status": obj.get("tracking_status"),
            "observed_at": obj.get("observed_at"),
            "assets": [BalanceAsset.from_dict(_item) for _item in obj["assets"]] if obj.get("assets") is not None else None,
            "wallet_versions": [WalletVersionBalance.from_dict(_item) for _item in obj["wallet_versions"]] if obj.get("wallet_versions") is not None else None,
            "reseed_contexts": [WalletFencedChainReseedContext.from_dict(_item) for _item in obj["reseed_contexts"]] if obj.get("reseed_contexts") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
