# coding: utf-8

"""
    x402api Public API

    Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.

    The version of the OpenAPI document: 1.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from x402api.models.wallet_observation_finality_enum import WalletObservationFinalityEnum
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class WalletChainReseedContext(BaseModel):
    """
    WalletChainReseedContext
    """ # noqa: E501
    checkpoint_id: UUID
    network: StrictStr
    finality: WalletObservationFinalityEnum
    manifest_digest: StrictStr
    policy_digest: StrictStr
    expected_generation: Annotated[int, Field(strict=True, ge=1)]
    expected_next_block_number: StrictStr
    expected_last_scanned_block_number: Optional[StrictStr]
    expected_last_scanned_block_hash: StrictStr
    expected_review_required_at: datetime
    expected_review_error_code: StrictStr
    observed_at: datetime
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["checkpoint_id", "network", "finality", "manifest_digest", "policy_digest", "expected_generation", "expected_next_block_number", "expected_last_scanned_block_number", "expected_last_scanned_block_hash", "expected_review_required_at", "expected_review_error_code", "observed_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WalletChainReseedContext from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if expected_last_scanned_block_number (nullable) is None
        # and model_fields_set contains the field
        if self.expected_last_scanned_block_number is None and "expected_last_scanned_block_number" in self.model_fields_set:
            _dict['expected_last_scanned_block_number'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WalletChainReseedContext from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "checkpoint_id": obj.get("checkpoint_id"),
            "network": obj.get("network"),
            "finality": obj.get("finality"),
            "manifest_digest": obj.get("manifest_digest"),
            "policy_digest": obj.get("policy_digest"),
            "expected_generation": obj.get("expected_generation"),
            "expected_next_block_number": obj.get("expected_next_block_number"),
            "expected_last_scanned_block_number": obj.get("expected_last_scanned_block_number"),
            "expected_last_scanned_block_hash": obj.get("expected_last_scanned_block_hash"),
            "expected_review_required_at": obj.get("expected_review_required_at"),
            "expected_review_error_code": obj.get("expected_review_error_code"),
            "observed_at": obj.get("observed_at")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
